apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    app: uberapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9099
      nodePort: 31000

